version: '3'

services:
  db:
    container_name: db_mysql
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=root_dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_USERNAME=dev
      - KC_DB_PASSWORD=dev
      - KC_DB_URL_HOST=db
      - KC_DB_URL_PORT=3306
      - KC_DB_SCHEMA=keycloak
    ports:
      - 8081:8080
    command: start-dev
    depends_on:
      - db
